server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: rick
    password: rick
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    service-url:
      defaultZone: http://rick:rick@localhost:8761/eureka/ #Eureka Server注册服务的地址